// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnisAIu8vJ6xngAG3dwQKo3Efvsz2jidA',
    appId: '1:300472710190:android:439dcba88bb3824b935bbf',
    messagingSenderId: '300472710190',
    projectId: 'sparkapp-3ceb5',
    storageBucket: 'sparkapp-3ceb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7gYVUhcHIdBUuT_zZH-mXAuky2xBn6GA',
    appId: '1:300472710190:ios:f20b0286dfffa39b935bbf',
    messagingSenderId: '300472710190',
    projectId: 'sparkapp-3ceb5',
    storageBucket: 'sparkapp-3ceb5.firebasestorage.app',
    iosBundleId: 'com.example.sparkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7gYVUhcHIdBUuT_zZH-mXAuky2xBn6GA',
    appId: '1:300472710190:ios:f20b0286dfffa39b935bbf',
    messagingSenderId: '300472710190',
    projectId: 'sparkapp-3ceb5',
    storageBucket: 'sparkapp-3ceb5.firebasestorage.app',
    iosBundleId: 'com.example.sparkapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWqsfF4AgsWp11q5S8Xy444XrlnUAkhYA',
    appId: '1:300472710190:web:33c07f8505b7ef7a935bbf',
    messagingSenderId: '300472710190',
    projectId: 'sparkapp-3ceb5',
    authDomain: 'sparkapp-3ceb5.firebaseapp.com',
    storageBucket: 'sparkapp-3ceb5.firebasestorage.app',
    measurementId: 'G-TE0YVPJJSF',
  );
}
